### ISSUE TITLE
Use the glTF extensions to use all the components of Rhinos PBR material

### ISSUE THREAD

**Issue by jrz371** [Stykka/glTF-Bin#19]
Rhinos PBR material supports sheen, clearcoat, and refraction. It looks like they might line up with these glTF extensions. Adding these should fill out the PBR spec on exported models.

[glTF Sheen](https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Khronos/KHR_materials_sheen/README.md)
[glTF Clearcoat](https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Khronos/KHR_materials_clearcoat/README.md)
[glTF Transmission](https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Khronos/KHR_materials_transmission/README.md)

**Comment by jrz371** [comment]
+1 request
https://discourse.mcneel.com/t/gltf-binexport/114378/40

**Comment by jrz371** [comment]
The sheen extension doesn't seem to match up very well with Rhino so I've excluded it for now

**Comment by marikaalmgren** [comment]
Seems to be ok.
