### ISSUE TITLE
Gamma correction for textures and colors

### ISSUE THREAD

**Issue by Doerge** [Stykka/glTF-Bin#3]
It's unclear to me if glTF clearly defines the colorspaces of it's inputs.
Threejs have [these expectations](https://threejs.org/docs/#examples/en/loaders/GLTFLoader) for the color space:
> Textures containing color information (.map, .emissiveMap, and .specularMap) always use sRGB colorspace in glTF, while vertex colors and material properties (.color, .emissive, .specular) use linear colorspace.

I'm also unsure how Rhino handles color spaces. If it's possible to somehow glean that info from Rhino, it should be used to properly convert textures and colors to what glTF expects.

If there is no universal spec for glTF colorspaces, then it should be a user setting.

**Comment by jrz371** [comment]
Hi,

The Rhino info for this is contained in the [Rhino.Render.LinearWorkflow](https://developer.rhino3d.com/api/RhinoCommon/html/T_Rhino_Render_LinearWorkflow.htm). It can be obtained from the RhinoDoc.RenderSettings.LinearWorkflow. I can fix this but I'm still busy with issue #2.

**Comment by Doerge** [comment]
Great! If you work on it, verify/fix the colorspace conversion functions. I rushed through it based on dubious sources.
