### ISSUE TITLE
Detect and handle bump maps

### ISSUE THREAD

**Issue by Doerge** [Stykka/glTF-Bin#32]
Exporting a bump map, messes up in the exported model. The broken normals in the ModelViewer looks like we should convert bump to normal before writing it into the gltf.
<img width="890" alt="Screenshot 2021-02-14 at 17 01 56" src="https://user-images.githubusercontent.com/3216279/107881842-64f14900-6ee6-11eb-9063-d1b873b027d0.png">

<img width="807" alt="Screenshot 2021-02-14 at 17 01 32" src="https://user-images.githubusercontent.com/3216279/107881839-63c01c00-6ee6-11eb-84b3-2bd9fb3086c9.png">

It's outside the scope of this project to create a converter. Maybe we should just detect if the map is a not a normal map, and warn the user.

**Comment by jrz371** [comment]
Hi,

I think this is something we can handle and I'm gonna take a crack at this next. Normal maps can be created from bump maps using a Sobel filter.

https://en.wikipedia.org/wiki/Sobel_operator

We can check if it's a normal map from Rhino

https://developer.rhino3d.com/api/RhinoCommon/html/M_Rhino_Render_RenderTexture_IsNormalMap.htm

**Comment by Doerge** [comment]
There are many settings for the conversion, which makes it hard to do a  universal automatic conversion.
See this link: https://cpetry.github.io/NormalMap-Online/

_A_ conversion is better than no conversion, so if you can pull it off it'd be awesome!

**Comment by jrz371** [comment]
I've added the conversion to pull #35. This conversion is essentially the same as done internally with Rhino so the output should match Rhinos display fairly closely. I've also logged a bug in Rhino to have Rhino handle the conversion but that may not make it in Rhino anytime soon.

**Comment by Doerge** [comment]
Solved by #35
