### ISSUE TITLE
SanitizeRhinoObjects for Blocks return null material

### ISSUE THREAD

**Issue by Doerge** [Stykka/glTF-Bin#38]
For e.g. Blocks, the mat is null when reaching this line.
https://github.com/Stykka/glTF-Bin/blob/7446876e116eb94716098f56fd2ce4e9620500ad/glTF-BinExporter/GlTFUtils.cs#L88

**Comment by jrz371** [comment]
Do you have an example file? I can't reproduce this

**Comment by Doerge** [comment]
This is no longer valid after #39
