### ISSUE TITLE
Add options to disregard certain mesh data

### ISSUE THREAD

**Issue by jrz371** [Stykka/glTF-Bin#48]
![image](https://user-images.githubusercontent.com/16514346/113832621-74c43580-9791-11eb-9303-6a8bcd52d88c.png)
Vertex colors can be supported in the mesh attributes COLOR_0 slot in glTF. Triangles are the only polygon type supported by glTF so we can disregard that option.

**Comment by Doerge** [comment]
Currently we use the render mesh.
What is the alternative? I.e. unchecked for obj? Does it only export `Mesh` then?

**Comment by jrz371** [comment]
It looks like draco compression encodes the vertex colors in ARGB order whereas glTF expects RGBA. I've got to add some changes into the draco interface that should hopefully be in Rhino 7.6.

**Comment by marikaalmgren** [comment]
This is the options I get now. Ok?
![gltf_export_option_mesh](https://user-images.githubusercontent.com/16681946/122728562-f3088200-d280-11eb-96f3-23e8a3687d79.PNG)

**Comment by jrz371** [comment]
That's fine
