### ISSUE TITLE
Add Mac project

### ISSUE THREAD

**Issue by jrz371** [Stykka/glTF-Bin#7]
There are good guidelines here for creating and organizing a cross platform project.

https://developer.rhino3d.com/6/guides/rhinocommon/your-first-plugin-crossplatform/

A Mac project should be added and the project structure should be organized as described in the guide.

**Comment by Doerge** [comment]
Stupid question: which project are you using on Windows? `glTF-BinExporter.csproj` or `glTF-BinExporterWin.csproj`? I'm using the former on Mac, and used to use the latter on Windows, but haven't tried it after I switched to `yak` for packaging.

**Comment by jrz371** [comment]
I use the Win project on Windows. This issue is mainly just a cleanup for the project structure. I don't think there will be much in the way of platform specific code.

**Comment by jrz371** [comment]
Fixed in #55
